// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ble_provider_id`, `core_error`, `normalize_provider_state`, `sessions`, `snapshot`, `with_session_mut`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Starts the one Rust-owned discovery session used by the Flutter application.
///
/// `enable_lan` is false only in deterministic unit tests. Product clients use
/// true after the platform has granted local-network access.
Future<DiscoveryBootstrap> discoveryStart({
  required int quicPort,
  required bool enableLan,
  required DiscoveryDeviceType deviceType,
}) => HaloRustLib.instance.api.crateApiDiscoveryStart(
  quicPort: quicPort,
  enableLan: enableLan,
  deviceType: deviceType,
);

/// Returns a newly sequenced descriptor for a native BLE driver to expose.
Future<Uint8List> discoveryRefreshBlePresence({required BigInt sessionId}) =>
    HaloRustLib.instance.api.crateApiDiscoveryRefreshBlePresence(
      sessionId: sessionId,
    );

/// Validates a raw platform BLE value in Rust and submits it to the shared manager.
Future<List<DiscoveryPeer>> discoverySubmitBle({
  required BigInt sessionId,
  required String platform,
  required List<int> descriptor,
}) => HaloRustLib.instance.api.crateApiDiscoverySubmitBle(
  sessionId: sessionId,
  platform: platform,
  descriptor: descriptor,
);

/// Normalizes raw native provider health into the Rust discovery event model.
Future<void> discoveryReportBleState({
  required BigInt sessionId,
  required String platform,
  required PlatformProviderState state,
  String? detail,
}) => HaloRustLib.instance.api.crateApiDiscoveryReportBleState(
  sessionId: sessionId,
  platform: platform,
  state: state,
  detail: detail,
);

Future<List<DiscoveryPeer>> discoverySnapshot({required BigInt sessionId}) =>
    HaloRustLib.instance.api.crateApiDiscoverySnapshot(sessionId: sessionId);

Future<void> discoveryStop({required BigInt sessionId}) =>
    HaloRustLib.instance.api.crateApiDiscoveryStop(sessionId: sessionId);

class DiscoveryBootstrap {
  final BigInt sessionId;
  final String presenceId;
  final DiscoveryDeviceType deviceType;
  final Uint8List blePresence;

  const DiscoveryBootstrap({
    required this.sessionId,
    required this.presenceId,
    required this.deviceType,
    required this.blePresence,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      presenceId.hashCode ^
      deviceType.hashCode ^
      blePresence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveryBootstrap &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          presenceId == other.presenceId &&
          deviceType == other.deviceType &&
          blePresence == other.blePresence;
}

enum DiscoveryDeviceType { unknown, android, ios, macos, windows, linux }

class DiscoveryPeer {
  final String presenceId;
  final DiscoveryDeviceType deviceType;
  final bool compatible;
  final BigInt capabilities;
  final List<String> sources;
  final String? bestEndpoint;
  final int candidateCount;
  final bool quarantined;

  const DiscoveryPeer({
    required this.presenceId,
    required this.deviceType,
    required this.compatible,
    required this.capabilities,
    required this.sources,
    this.bestEndpoint,
    required this.candidateCount,
    required this.quarantined,
  });

  @override
  int get hashCode =>
      presenceId.hashCode ^
      deviceType.hashCode ^
      compatible.hashCode ^
      capabilities.hashCode ^
      sources.hashCode ^
      bestEndpoint.hashCode ^
      candidateCount.hashCode ^
      quarantined.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveryPeer &&
          runtimeType == other.runtimeType &&
          presenceId == other.presenceId &&
          deviceType == other.deviceType &&
          compatible == other.compatible &&
          capabilities == other.capabilities &&
          sources == other.sources &&
          bestEndpoint == other.bestEndpoint &&
          candidateCount == other.candidateCount &&
          quarantined == other.quarantined;
}

@freezed
sealed class HaloApiError with _$HaloApiError implements FrbException {
  const HaloApiError._();

  const factory HaloApiError.invalidArgument({required String message}) =
      HaloApiError_InvalidArgument;
  const factory HaloApiError.sessionNotFound() = HaloApiError_SessionNotFound;
  const factory HaloApiError.core({required String message}) =
      HaloApiError_Core;
  const factory HaloApiError.internalState() = HaloApiError_InternalState;
}

enum PlatformProviderState {
  starting,
  ready,
  degraded,
  permissionRequired,
  permissionDenied,
  hardwareOff,
  unsupported,
  temporarilyUnavailable,
  stopped,
}
