// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class HaloRustLib
    extends
        BaseEntrypoint<HaloRustLibApi, HaloRustLibApiImpl, HaloRustLibWire> {
  @internal
  static final instance = HaloRustLib._();

  HaloRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    HaloRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required HaloRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<HaloRustLibApiImpl, HaloRustLibWire>
  get apiImplConstructor => HaloRustLibApiImpl.new;

  @override
  WireConstructor<HaloRustLibWire> get wireConstructor =>
      HaloRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1370488548;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'halo_ffi',
        ioDirectory: '../../crates/halo-ffi/target/release/',
        webPrefix: 'halo_ffi',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class HaloRustLibApi extends BaseApi {
  Future<List<DiscoveryProviderStatus>> crateApiDiscoveryProviderStatuses({
    required BigInt sessionId,
  });

  Future<Uint8List> crateApiDiscoveryRefreshBlePresence({
    required BigInt sessionId,
  });

  Future<void> crateApiDiscoveryReportBleState({
    required BigInt sessionId,
    required String platform,
    required PlatformProviderState state,
    String? detail,
  });

  Future<List<DiscoveryPeer>> crateApiDiscoverySnapshot({
    required BigInt sessionId,
  });

  Future<DiscoveryBootstrap> crateApiDiscoveryStart({
    required int quicPort,
    required bool enableLan,
    required DiscoveryDeviceType deviceType,
  });

  Future<void> crateApiDiscoveryStop({required BigInt sessionId});

  Future<List<DiscoveryPeer>> crateApiDiscoverySubmitBle({
    required BigInt sessionId,
    required String platform,
    required List<int> descriptor,
  });
}

class HaloRustLibApiImpl extends HaloRustLibApiImplPlatform
    implements HaloRustLibApi {
  HaloRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<DiscoveryProviderStatus>> crateApiDiscoveryProviderStatuses({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_discovery_provider_status,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoveryProviderStatusesConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryProviderStatusesConstMeta =>
      const TaskConstMeta(
        debugName: "discovery_provider_statuses",
        argNames: ["sessionId"],
      );

  @override
  Future<Uint8List> crateApiDiscoveryRefreshBlePresence({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoveryRefreshBlePresenceConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryRefreshBlePresenceConstMeta =>
      const TaskConstMeta(
        debugName: "discovery_refresh_ble_presence",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiDiscoveryReportBleState({
    required BigInt sessionId,
    required String platform,
    required PlatformProviderState state,
    String? detail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(platform, serializer);
          sse_encode_platform_provider_state(state, serializer);
          sse_encode_opt_String(detail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoveryReportBleStateConstMeta,
        argValues: [sessionId, platform, state, detail],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryReportBleStateConstMeta =>
      const TaskConstMeta(
        debugName: "discovery_report_ble_state",
        argNames: ["sessionId", "platform", "state", "detail"],
      );

  @override
  Future<List<DiscoveryPeer>> crateApiDiscoverySnapshot({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_discovery_peer,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoverySnapshotConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoverySnapshotConstMeta => const TaskConstMeta(
    debugName: "discovery_snapshot",
    argNames: ["sessionId"],
  );

  @override
  Future<DiscoveryBootstrap> crateApiDiscoveryStart({
    required int quicPort,
    required bool enableLan,
    required DiscoveryDeviceType deviceType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(quicPort, serializer);
          sse_encode_bool(enableLan, serializer);
          sse_encode_discovery_device_type(deviceType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_discovery_bootstrap,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoveryStartConstMeta,
        argValues: [quicPort, enableLan, deviceType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryStartConstMeta => const TaskConstMeta(
    debugName: "discovery_start",
    argNames: ["quicPort", "enableLan", "deviceType"],
  );

  @override
  Future<void> crateApiDiscoveryStop({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoveryStopConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryStopConstMeta =>
      const TaskConstMeta(debugName: "discovery_stop", argNames: ["sessionId"]);

  @override
  Future<List<DiscoveryPeer>> crateApiDiscoverySubmitBle({
    required BigInt sessionId,
    required String platform,
    required List<int> descriptor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(platform, serializer);
          sse_encode_list_prim_u_8_loose(descriptor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_discovery_peer,
          decodeErrorData: sse_decode_halo_api_error,
        ),
        constMeta: kCrateApiDiscoverySubmitBleConstMeta,
        argValues: [sessionId, platform, descriptor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoverySubmitBleConstMeta => const TaskConstMeta(
    debugName: "discovery_submit_ble",
    argNames: ["sessionId", "platform", "descriptor"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiscoveryBootstrap dco_decode_discovery_bootstrap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiscoveryBootstrap(
      sessionId: dco_decode_u_64(arr[0]),
      presenceId: dco_decode_String(arr[1]),
      deviceType: dco_decode_discovery_device_type(arr[2]),
      blePresence: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  DiscoveryDeviceType dco_decode_discovery_device_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiscoveryDeviceType.values[raw as int];
  }

  @protected
  DiscoveryPeer dco_decode_discovery_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DiscoveryPeer(
      presenceId: dco_decode_String(arr[0]),
      deviceType: dco_decode_discovery_device_type(arr[1]),
      compatible: dco_decode_bool(arr[2]),
      capabilities: dco_decode_u_64(arr[3]),
      sources: dco_decode_list_String(arr[4]),
      bestEndpoint: dco_decode_opt_String(arr[5]),
      candidateCount: dco_decode_u_32(arr[6]),
      quarantined: dco_decode_bool(arr[7]),
    );
  }

  @protected
  DiscoveryProviderStatus dco_decode_discovery_provider_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiscoveryProviderStatus(
      name: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      state: dco_decode_String(arr[2]),
      detail: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  HaloApiError dco_decode_halo_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HaloApiError_InvalidArgument(message: dco_decode_String(raw[1]));
      case 1:
        return HaloApiError_SessionNotFound();
      case 2:
        return HaloApiError_Core(message: dco_decode_String(raw[1]));
      case 3:
        return HaloApiError_InternalState();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DiscoveryPeer> dco_decode_list_discovery_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_discovery_peer).toList();
  }

  @protected
  List<DiscoveryProviderStatus> dco_decode_list_discovery_provider_status(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_discovery_provider_status)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformProviderState dco_decode_platform_provider_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlatformProviderState.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiscoveryBootstrap sse_decode_discovery_bootstrap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_presenceId = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_discovery_device_type(deserializer);
    var var_blePresence = sse_decode_list_prim_u_8_strict(deserializer);
    return DiscoveryBootstrap(
      sessionId: var_sessionId,
      presenceId: var_presenceId,
      deviceType: var_deviceType,
      blePresence: var_blePresence,
    );
  }

  @protected
  DiscoveryDeviceType sse_decode_discovery_device_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiscoveryDeviceType.values[inner];
  }

  @protected
  DiscoveryPeer sse_decode_discovery_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_presenceId = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_discovery_device_type(deserializer);
    var var_compatible = sse_decode_bool(deserializer);
    var var_capabilities = sse_decode_u_64(deserializer);
    var var_sources = sse_decode_list_String(deserializer);
    var var_bestEndpoint = sse_decode_opt_String(deserializer);
    var var_candidateCount = sse_decode_u_32(deserializer);
    var var_quarantined = sse_decode_bool(deserializer);
    return DiscoveryPeer(
      presenceId: var_presenceId,
      deviceType: var_deviceType,
      compatible: var_compatible,
      capabilities: var_capabilities,
      sources: var_sources,
      bestEndpoint: var_bestEndpoint,
      candidateCount: var_candidateCount,
      quarantined: var_quarantined,
    );
  }

  @protected
  DiscoveryProviderStatus sse_decode_discovery_provider_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_detail = sse_decode_opt_String(deserializer);
    return DiscoveryProviderStatus(
      name: var_name,
      kind: var_kind,
      state: var_state,
      detail: var_detail,
    );
  }

  @protected
  HaloApiError sse_decode_halo_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_message = sse_decode_String(deserializer);
        return HaloApiError_InvalidArgument(message: var_message);
      case 1:
        return HaloApiError_SessionNotFound();
      case 2:
        var var_message = sse_decode_String(deserializer);
        return HaloApiError_Core(message: var_message);
      case 3:
        return HaloApiError_InternalState();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiscoveryPeer> sse_decode_list_discovery_peer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiscoveryPeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_discovery_peer(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiscoveryProviderStatus> sse_decode_list_discovery_provider_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiscoveryProviderStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_discovery_provider_status(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformProviderState sse_decode_platform_provider_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlatformProviderState.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_discovery_bootstrap(
    DiscoveryBootstrap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_String(self.presenceId, serializer);
    sse_encode_discovery_device_type(self.deviceType, serializer);
    sse_encode_list_prim_u_8_strict(self.blePresence, serializer);
  }

  @protected
  void sse_encode_discovery_device_type(
    DiscoveryDeviceType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_discovery_peer(DiscoveryPeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.presenceId, serializer);
    sse_encode_discovery_device_type(self.deviceType, serializer);
    sse_encode_bool(self.compatible, serializer);
    sse_encode_u_64(self.capabilities, serializer);
    sse_encode_list_String(self.sources, serializer);
    sse_encode_opt_String(self.bestEndpoint, serializer);
    sse_encode_u_32(self.candidateCount, serializer);
    sse_encode_bool(self.quarantined, serializer);
  }

  @protected
  void sse_encode_discovery_provider_status(
    DiscoveryProviderStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_opt_String(self.detail, serializer);
  }

  @protected
  void sse_encode_halo_api_error(HaloApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HaloApiError_InvalidArgument(message: final message):
        sse_encode_i_32(0, serializer);
        sse_encode_String(message, serializer);
      case HaloApiError_SessionNotFound():
        sse_encode_i_32(1, serializer);
      case HaloApiError_Core(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case HaloApiError_InternalState():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_discovery_peer(
    List<DiscoveryPeer> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_discovery_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_discovery_provider_status(
    List<DiscoveryProviderStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_discovery_provider_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_platform_provider_state(
    PlatformProviderState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
