// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/pairing_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class HaloRustLibApiImplPlatform extends BaseApiImpl<HaloRustLibWire> {
  HaloRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthenticatedSessionInfo dco_decode_authenticated_session_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DiscoveryBootstrap dco_decode_discovery_bootstrap(dynamic raw);

  @protected
  DiscoveryDeviceType dco_decode_discovery_device_type(dynamic raw);

  @protected
  DiscoveryPeer dco_decode_discovery_peer(dynamic raw);

  @protected
  DiscoveryProviderStatus dco_decode_discovery_provider_status(dynamic raw);

  @protected
  HaloApiError dco_decode_halo_api_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuthenticatedSessionInfo> dco_decode_list_authenticated_session_info(
    dynamic raw,
  );

  @protected
  List<DiscoveryPeer> dco_decode_list_discovery_peer(dynamic raw);

  @protected
  List<DiscoveryProviderStatus> dco_decode_list_discovery_provider_status(
    dynamic raw,
  );

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PairingEvent> dco_decode_list_pairing_event(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RememberedPeerInfo> dco_decode_list_remembered_peer_info(dynamic raw);

  @protected
  List<TransferEvent> dco_decode_list_transfer_event(dynamic raw);

  @protected
  List<TransferFileSource> dco_decode_list_transfer_file_source(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PairingBootstrap dco_decode_pairing_bootstrap(dynamic raw);

  @protected
  PairingEvent dco_decode_pairing_event(dynamic raw);

  @protected
  PairingEventKind dco_decode_pairing_event_kind(dynamic raw);

  @protected
  PlatformPairingChannelState dco_decode_platform_pairing_channel_state(
    dynamic raw,
  );

  @protected
  PlatformPairingRole dco_decode_platform_pairing_role(dynamic raw);

  @protected
  PlatformProviderState dco_decode_platform_provider_state(dynamic raw);

  @protected
  PlatformTlsIdentity dco_decode_platform_tls_identity(dynamic raw);

  @protected
  RememberedPeerInfo dco_decode_remembered_peer_info(dynamic raw);

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw);

  @protected
  TransferEvent dco_decode_transfer_event(dynamic raw);

  @protected
  TransferEventKind dco_decode_transfer_event_kind(dynamic raw);

  @protected
  TransferFileSource dco_decode_transfer_file_source(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthenticatedSessionInfo sse_decode_authenticated_session_info(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DiscoveryBootstrap sse_decode_discovery_bootstrap(
    SseDeserializer deserializer,
  );

  @protected
  DiscoveryDeviceType sse_decode_discovery_device_type(
    SseDeserializer deserializer,
  );

  @protected
  DiscoveryPeer sse_decode_discovery_peer(SseDeserializer deserializer);

  @protected
  DiscoveryProviderStatus sse_decode_discovery_provider_status(
    SseDeserializer deserializer,
  );

  @protected
  HaloApiError sse_decode_halo_api_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuthenticatedSessionInfo> sse_decode_list_authenticated_session_info(
    SseDeserializer deserializer,
  );

  @protected
  List<DiscoveryPeer> sse_decode_list_discovery_peer(
    SseDeserializer deserializer,
  );

  @protected
  List<DiscoveryProviderStatus> sse_decode_list_discovery_provider_status(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<PairingEvent> sse_decode_list_pairing_event(
    SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RememberedPeerInfo> sse_decode_list_remembered_peer_info(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferEvent> sse_decode_list_transfer_event(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferFileSource> sse_decode_list_transfer_file_source(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PairingBootstrap sse_decode_pairing_bootstrap(SseDeserializer deserializer);

  @protected
  PairingEvent sse_decode_pairing_event(SseDeserializer deserializer);

  @protected
  PairingEventKind sse_decode_pairing_event_kind(SseDeserializer deserializer);

  @protected
  PlatformPairingChannelState sse_decode_platform_pairing_channel_state(
    SseDeserializer deserializer,
  );

  @protected
  PlatformPairingRole sse_decode_platform_pairing_role(
    SseDeserializer deserializer,
  );

  @protected
  PlatformProviderState sse_decode_platform_provider_state(
    SseDeserializer deserializer,
  );

  @protected
  PlatformTlsIdentity sse_decode_platform_tls_identity(
    SseDeserializer deserializer,
  );

  @protected
  RememberedPeerInfo sse_decode_remembered_peer_info(
    SseDeserializer deserializer,
  );

  @protected
  TransferDirection sse_decode_transfer_direction(SseDeserializer deserializer);

  @protected
  TransferEvent sse_decode_transfer_event(SseDeserializer deserializer);

  @protected
  TransferEventKind sse_decode_transfer_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  TransferFileSource sse_decode_transfer_file_source(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_authenticated_session_info(
    AuthenticatedSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_discovery_bootstrap(
    DiscoveryBootstrap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_device_type(
    DiscoveryDeviceType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_peer(DiscoveryPeer self, SseSerializer serializer);

  @protected
  void sse_encode_discovery_provider_status(
    DiscoveryProviderStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_halo_api_error(HaloApiError self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_authenticated_session_info(
    List<AuthenticatedSessionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_discovery_peer(
    List<DiscoveryPeer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_discovery_provider_status(
    List<DiscoveryProviderStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pairing_event(
    List<PairingEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remembered_peer_info(
    List<RememberedPeerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_event(
    List<TransferEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_file_source(
    List<TransferFileSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_bootstrap(
    PairingBootstrap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_event(PairingEvent self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_event_kind(
    PairingEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_pairing_channel_state(
    PlatformPairingChannelState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_pairing_role(
    PlatformPairingRole self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_provider_state(
    PlatformProviderState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_tls_identity(
    PlatformTlsIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remembered_peer_info(
    RememberedPeerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_direction(
    TransferDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_event(TransferEvent self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_event_kind(
    TransferEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_file_source(
    TransferFileSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class HaloRustLibWire implements BaseWire {
  factory HaloRustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      HaloRustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  HaloRustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
