// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_error`, `pairing_error`, `pairing_sessions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PairingSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`

Future<PairingBootstrap> pairingStart({
  Uint8List? identityBlob,
  required String trustStoreDirectory,
}) => HaloRustLib.instance.api.crateApiPairingApiPairingStart(
  identityBlob: identityBlob,
  trustStoreDirectory: trustStoreDirectory,
);

Future<void> pairingConnect({
  required BigInt sessionId,
  required String peerPresenceId,
  required List<String> endpoints,
}) => HaloRustLib.instance.api.crateApiPairingApiPairingConnect(
  sessionId: sessionId,
  peerPresenceId: peerPresenceId,
  endpoints: endpoints,
);

Future<List<PairingEvent>> pairingEvents({
  required BigInt sessionId,
  required BigInt afterEventId,
}) => HaloRustLib.instance.api.crateApiPairingApiPairingEvents(
  sessionId: sessionId,
  afterEventId: afterEventId,
);

Future<void> pairingRespond({
  required BigInt sessionId,
  required BigInt requestId,
  required bool accepted,
}) => HaloRustLib.instance.api.crateApiPairingApiPairingRespond(
  sessionId: sessionId,
  requestId: requestId,
  accepted: accepted,
);

Future<void> pairingStop({required BigInt sessionId}) => HaloRustLib
    .instance
    .api
    .crateApiPairingApiPairingStop(sessionId: sessionId);

class PairingBootstrap {
  final BigInt sessionId;
  final int listenPort;

  /// Present only for a newly generated identity. The caller must persist it
  /// using the platform protected-blob adapter before advertising the port.
  final Uint8List? identityBlobToPersist;

  const PairingBootstrap({
    required this.sessionId,
    required this.listenPort,
    this.identityBlobToPersist,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ listenPort.hashCode ^ identityBlobToPersist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingBootstrap &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          listenPort == other.listenPort &&
          identityBlobToPersist == other.identityBlobToPersist;
}

class PairingEvent {
  final BigInt eventId;
  final BigInt? requestId;
  final PairingEventKind kind;
  final String? peerPresenceId;
  final String? peerFingerprint;
  final String? shortCode;
  final bool alreadyTrusted;
  final String? detail;

  const PairingEvent({
    required this.eventId,
    this.requestId,
    required this.kind,
    this.peerPresenceId,
    this.peerFingerprint,
    this.shortCode,
    required this.alreadyTrusted,
    this.detail,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      requestId.hashCode ^
      kind.hashCode ^
      peerPresenceId.hashCode ^
      peerFingerprint.hashCode ^
      shortCode.hashCode ^
      alreadyTrusted.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          requestId == other.requestId &&
          kind == other.kind &&
          peerPresenceId == other.peerPresenceId &&
          peerFingerprint == other.peerFingerprint &&
          shortCode == other.shortCode &&
          alreadyTrusted == other.alreadyTrusted &&
          detail == other.detail;
}

enum PairingEventKind {
  connecting,
  codeAvailable,
  confirmationRequired,
  trusted,
  rejected,
  identityChanged,
  timedOut,
  cancelled,
  failed,
}
