// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -636126895;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__discovery_provider_statuses_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_provider_statuses",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_provider_statuses(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_refresh_ble_presence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_refresh_ble_presence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_refresh_ble_presence(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_report_ble_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_report_ble_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_platform = <String>::sse_decode(&mut deserializer);
            let api_state = <crate::api::PlatformProviderState>::sse_decode(&mut deserializer);
            let api_detail = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_report_ble_state(
                        api_session_id,
                        api_platform,
                        api_state,
                        api_detail,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_snapshot(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_quic_port = <u16>::sse_decode(&mut deserializer);
            let api_enable_lan = <bool>::sse_decode(&mut deserializer);
            let api_device_type = <crate::api::DiscoveryDeviceType>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_start(
                        api_quic_port,
                        api_enable_lan,
                        api_device_type,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_stop(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery_submit_ble_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "discovery_submit_ble",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_platform = <String>::sse_decode(&mut deserializer);
            let api_descriptor = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::discovery_submit_ble(
                        api_session_id,
                        api_platform,
                        api_descriptor,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_attach_platform_channel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_attach_platform_channel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_peer_presence_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_role =
                <crate::api::pairing_api::PlatformPairingRole>::sse_decode(&mut deserializer);
            let api_channel_binding = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_attach_platform_channel(
                        api_session_id,
                        api_peer_presence_id,
                        api_role,
                        api_channel_binding,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_authenticated_sessions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_authenticated_sessions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok =
                        crate::api::pairing_api::pairing_authenticated_sessions(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_close_platform_channel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_close_platform_channel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_channel_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_close_platform_channel(
                        api_session_id,
                        api_channel_id,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_connect_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_connect",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_peer_presence_id = <String>::sse_decode(&mut deserializer);
            let api_endpoints = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_connect(
                        api_session_id,
                        api_peer_presence_id,
                        api_endpoints,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_create_platform_tls_identity_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_create_platform_tls_identity",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok =
                        crate::api::pairing_api::pairing_create_platform_tls_identity()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_drain_platform_frames_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_drain_platform_frames",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_channel_id = <u64>::sse_decode(&mut deserializer);
            let api_maximum_frames = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_drain_platform_frames(
                        api_session_id,
                        api_channel_id,
                        api_maximum_frames,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_after_event_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_events(
                        api_session_id,
                        api_after_event_id,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_platform_channel_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_platform_channel_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_channel_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_platform_channel_state(
                        api_session_id,
                        api_channel_id,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_respond_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_respond",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_request_id = <u64>::sse_decode(&mut deserializer);
            let api_accepted = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_respond(
                        api_session_id,
                        api_request_id,
                        api_accepted,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_identity_blob = <Option<Vec<u8>>>::sse_decode(&mut deserializer);
            let api_trust_store_directory = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_start(
                        api_identity_blob,
                        api_trust_store_directory,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_stop(api_session_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_submit_platform_frame_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_submit_platform_frame",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_channel_id = <u64>::sse_decode(&mut deserializer);
            let api_frame = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_submit_platform_frame(
                        api_session_id,
                        api_channel_id,
                        api_frame,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_transfer_cancel_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_transfer_cancel",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_transfer_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_transfer_cancel(
                        api_session_id,
                        api_transfer_id,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_transfer_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_transfer_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_after_event_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_transfer_events(
                        api_session_id,
                        api_after_event_id,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_transfer_respond_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_transfer_respond",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_request_id = <u64>::sse_decode(&mut deserializer);
            let api_accepted = <bool>::sse_decode(&mut deserializer);
            let api_staging_directory = <Option<String>>::sse_decode(&mut deserializer);
            let api_destination_directory = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_transfer_respond(
                        api_session_id,
                        api_request_id,
                        api_accepted,
                        api_staging_directory,
                        api_destination_directory,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing_api__pairing_transfer_send_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_transfer_send_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u64>::sse_decode(&mut deserializer);
            let api_authenticated_session_id = <u64>::sse_decode(&mut deserializer);
            let api_source_path = <String>::sse_decode(&mut deserializer);
            let api_advertised_name = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::HaloApiError>((move || {
                    let output_ok = crate::api::pairing_api::pairing_transfer_send_file(
                        api_session_id,
                        api_authenticated_session_id,
                        api_source_path,
                        api_advertised_name,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::pairing_api::AuthenticatedSessionInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <u64>::sse_decode(deserializer);
        let mut var_peerFingerprint = <String>::sse_decode(deserializer);
        let mut var_peerPresenceId = <Option<String>>::sse_decode(deserializer);
        return crate::api::pairing_api::AuthenticatedSessionInfo {
            session_id: var_sessionId,
            peer_fingerprint: var_peerFingerprint,
            peer_presence_id: var_peerPresenceId,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::DiscoveryBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <u64>::sse_decode(deserializer);
        let mut var_presenceId = <String>::sse_decode(deserializer);
        let mut var_deviceType = <crate::api::DiscoveryDeviceType>::sse_decode(deserializer);
        let mut var_blePresence = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::DiscoveryBootstrap {
            session_id: var_sessionId,
            presence_id: var_presenceId,
            device_type: var_deviceType,
            ble_presence: var_blePresence,
        };
    }
}

impl SseDecode for crate::api::DiscoveryDeviceType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::DiscoveryDeviceType::Unknown,
            1 => crate::api::DiscoveryDeviceType::Android,
            2 => crate::api::DiscoveryDeviceType::Ios,
            3 => crate::api::DiscoveryDeviceType::Macos,
            4 => crate::api::DiscoveryDeviceType::Windows,
            5 => crate::api::DiscoveryDeviceType::Linux,
            _ => unreachable!("Invalid variant for DiscoveryDeviceType: {}", inner),
        };
    }
}

impl SseDecode for crate::api::DiscoveryPeer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_presenceId = <String>::sse_decode(deserializer);
        let mut var_deviceType = <crate::api::DiscoveryDeviceType>::sse_decode(deserializer);
        let mut var_compatible = <bool>::sse_decode(deserializer);
        let mut var_capabilities = <u64>::sse_decode(deserializer);
        let mut var_sources = <Vec<String>>::sse_decode(deserializer);
        let mut var_bestEndpoint = <Option<String>>::sse_decode(deserializer);
        let mut var_candidateEndpoints = <Vec<String>>::sse_decode(deserializer);
        let mut var_candidateCount = <u32>::sse_decode(deserializer);
        let mut var_quarantined = <bool>::sse_decode(deserializer);
        return crate::api::DiscoveryPeer {
            presence_id: var_presenceId,
            device_type: var_deviceType,
            compatible: var_compatible,
            capabilities: var_capabilities,
            sources: var_sources,
            best_endpoint: var_bestEndpoint,
            candidate_endpoints: var_candidateEndpoints,
            candidate_count: var_candidateCount,
            quarantined: var_quarantined,
        };
    }
}

impl SseDecode for crate::api::DiscoveryProviderStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_detail = <Option<String>>::sse_decode(deserializer);
        return crate::api::DiscoveryProviderStatus {
            name: var_name,
            kind: var_kind,
            state: var_state,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::HaloApiError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::HaloApiError::InvalidArgument {
                    message: var_message,
                };
            }
            1 => {
                return crate::api::HaloApiError::SessionNotFound;
            }
            2 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::HaloApiError::Core {
                    message: var_message,
                };
            }
            3 => {
                return crate::api::HaloApiError::InternalState;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::pairing_api::AuthenticatedSessionInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::pairing_api::AuthenticatedSessionInfo>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::DiscoveryPeer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::DiscoveryPeer>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::DiscoveryProviderStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::DiscoveryProviderStatus>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<Vec<u8>>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::pairing_api::PairingEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::pairing_api::PairingEvent>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::pairing_api::TransferEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::pairing_api::TransferEvent>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::pairing_api::PairingBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <u64>::sse_decode(deserializer);
        let mut var_listenPort = <u16>::sse_decode(deserializer);
        let mut var_identityBlobToPersist = <Option<Vec<u8>>>::sse_decode(deserializer);
        return crate::api::pairing_api::PairingBootstrap {
            session_id: var_sessionId,
            listen_port: var_listenPort,
            identity_blob_to_persist: var_identityBlobToPersist,
        };
    }
}

impl SseDecode for crate::api::pairing_api::PairingEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <u64>::sse_decode(deserializer);
        let mut var_requestId = <Option<u64>>::sse_decode(deserializer);
        let mut var_kind = <crate::api::pairing_api::PairingEventKind>::sse_decode(deserializer);
        let mut var_peerPresenceId = <Option<String>>::sse_decode(deserializer);
        let mut var_peerFingerprint = <Option<String>>::sse_decode(deserializer);
        let mut var_shortCode = <Option<String>>::sse_decode(deserializer);
        let mut var_alreadyTrusted = <bool>::sse_decode(deserializer);
        let mut var_authenticatedSessionId = <Option<u64>>::sse_decode(deserializer);
        let mut var_detail = <Option<String>>::sse_decode(deserializer);
        return crate::api::pairing_api::PairingEvent {
            event_id: var_eventId,
            request_id: var_requestId,
            kind: var_kind,
            peer_presence_id: var_peerPresenceId,
            peer_fingerprint: var_peerFingerprint,
            short_code: var_shortCode,
            already_trusted: var_alreadyTrusted,
            authenticated_session_id: var_authenticatedSessionId,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::pairing_api::PairingEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pairing_api::PairingEventKind::Connecting,
            1 => crate::api::pairing_api::PairingEventKind::CodeAvailable,
            2 => crate::api::pairing_api::PairingEventKind::ConfirmationRequired,
            3 => crate::api::pairing_api::PairingEventKind::Trusted,
            4 => crate::api::pairing_api::PairingEventKind::Rejected,
            5 => crate::api::pairing_api::PairingEventKind::IdentityChanged,
            6 => crate::api::pairing_api::PairingEventKind::TimedOut,
            7 => crate::api::pairing_api::PairingEventKind::Cancelled,
            8 => crate::api::pairing_api::PairingEventKind::Failed,
            9 => crate::api::pairing_api::PairingEventKind::Disconnected,
            _ => unreachable!("Invalid variant for PairingEventKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pairing_api::PlatformPairingChannelState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pairing_api::PlatformPairingChannelState::Pending,
            1 => crate::api::pairing_api::PlatformPairingChannelState::Authenticated,
            2 => crate::api::pairing_api::PlatformPairingChannelState::Failed,
            _ => unreachable!("Invalid variant for PlatformPairingChannelState: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pairing_api::PlatformPairingRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pairing_api::PlatformPairingRole::Initiator,
            1 => crate::api::pairing_api::PlatformPairingRole::Responder,
            _ => unreachable!("Invalid variant for PlatformPairingRole: {}", inner),
        };
    }
}

impl SseDecode for crate::api::PlatformProviderState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::PlatformProviderState::Starting,
            1 => crate::api::PlatformProviderState::Ready,
            2 => crate::api::PlatformProviderState::Degraded,
            3 => crate::api::PlatformProviderState::PermissionRequired,
            4 => crate::api::PlatformProviderState::PermissionDenied,
            5 => crate::api::PlatformProviderState::HardwareOff,
            6 => crate::api::PlatformProviderState::Unsupported,
            7 => crate::api::PlatformProviderState::TemporarilyUnavailable,
            8 => crate::api::PlatformProviderState::Stopped,
            _ => unreachable!("Invalid variant for PlatformProviderState: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pairing_api::PlatformTlsIdentity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_certificateDer = <Vec<u8>>::sse_decode(deserializer);
        let mut var_privateKeyX963 = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::pairing_api::PlatformTlsIdentity {
            certificate_der: var_certificateDer,
            private_key_x963: var_privateKeyX963,
        };
    }
}

impl SseDecode for crate::api::pairing_api::TransferDirection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pairing_api::TransferDirection::Sending,
            1 => crate::api::pairing_api::TransferDirection::Receiving,
            _ => unreachable!("Invalid variant for TransferDirection: {}", inner),
        };
    }
}

impl SseDecode for crate::api::pairing_api::TransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <u64>::sse_decode(deserializer);
        let mut var_requestId = <Option<u64>>::sse_decode(deserializer);
        let mut var_authenticatedSessionId = <u64>::sse_decode(deserializer);
        let mut var_transferId = <String>::sse_decode(deserializer);
        let mut var_direction =
            <crate::api::pairing_api::TransferDirection>::sse_decode(deserializer);
        let mut var_kind = <crate::api::pairing_api::TransferEventKind>::sse_decode(deserializer);
        let mut var_fileName = <String>::sse_decode(deserializer);
        let mut var_fileSize = <u64>::sse_decode(deserializer);
        let mut var_transferredBytes = <u64>::sse_decode(deserializer);
        let mut var_finalPath = <Option<String>>::sse_decode(deserializer);
        let mut var_detail = <Option<String>>::sse_decode(deserializer);
        return crate::api::pairing_api::TransferEvent {
            event_id: var_eventId,
            request_id: var_requestId,
            authenticated_session_id: var_authenticatedSessionId,
            transfer_id: var_transferId,
            direction: var_direction,
            kind: var_kind,
            file_name: var_fileName,
            file_size: var_fileSize,
            transferred_bytes: var_transferredBytes,
            final_path: var_finalPath,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::pairing_api::TransferEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::pairing_api::TransferEventKind::OfferReceived,
            1 => crate::api::pairing_api::TransferEventKind::AwaitingDecision,
            2 => crate::api::pairing_api::TransferEventKind::Transferring,
            3 => crate::api::pairing_api::TransferEventKind::Completed,
            4 => crate::api::pairing_api::TransferEventKind::Rejected,
            5 => crate::api::pairing_api::TransferEventKind::Cancelled,
            6 => crate::api::pairing_api::TransferEventKind::Failed,
            _ => unreachable!("Invalid variant for TransferEventKind: {}", inner),
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__discovery_provider_statuses_impl(port, ptr, rust_vec_len, data_len),
        2 => {
            wire__crate__api__discovery_refresh_ble_presence_impl(port, ptr, rust_vec_len, data_len)
        }
        3 => wire__crate__api__discovery_report_ble_state_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__discovery_snapshot_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__discovery_start_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__discovery_stop_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__discovery_submit_ble_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__pairing_api__pairing_attach_platform_channel_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__pairing_api__pairing_authenticated_sessions_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        10 => wire__crate__api__pairing_api__pairing_close_platform_channel_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => {
            wire__crate__api__pairing_api__pairing_connect_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api__pairing_api__pairing_create_platform_tls_identity_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api__pairing_api__pairing_drain_platform_frames_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => wire__crate__api__pairing_api__pairing_events_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__pairing_api__pairing_platform_channel_state_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        16 => {
            wire__crate__api__pairing_api__pairing_respond_impl(port, ptr, rust_vec_len, data_len)
        }
        17 => wire__crate__api__pairing_api__pairing_start_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__api__pairing_api__pairing_stop_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api__pairing_api__pairing_submit_platform_frame_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        20 => wire__crate__api__pairing_api__pairing_transfer_cancel_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        21 => wire__crate__api__pairing_api__pairing_transfer_events_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        22 => wire__crate__api__pairing_api__pairing_transfer_respond_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        23 => wire__crate__api__pairing_api__pairing_transfer_send_file_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::AuthenticatedSessionInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.peer_fingerprint.into_into_dart().into_dart(),
            self.peer_presence_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::AuthenticatedSessionInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::AuthenticatedSessionInfo>
    for crate::api::pairing_api::AuthenticatedSessionInfo
{
    fn into_into_dart(self) -> crate::api::pairing_api::AuthenticatedSessionInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiscoveryBootstrap {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.presence_id.into_into_dart().into_dart(),
            self.device_type.into_into_dart().into_dart(),
            self.ble_presence.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::DiscoveryBootstrap
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiscoveryBootstrap>
    for crate::api::DiscoveryBootstrap
{
    fn into_into_dart(self) -> crate::api::DiscoveryBootstrap {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiscoveryDeviceType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Unknown => 0.into_dart(),
            Self::Android => 1.into_dart(),
            Self::Ios => 2.into_dart(),
            Self::Macos => 3.into_dart(),
            Self::Windows => 4.into_dart(),
            Self::Linux => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::DiscoveryDeviceType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiscoveryDeviceType>
    for crate::api::DiscoveryDeviceType
{
    fn into_into_dart(self) -> crate::api::DiscoveryDeviceType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiscoveryPeer {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.presence_id.into_into_dart().into_dart(),
            self.device_type.into_into_dart().into_dart(),
            self.compatible.into_into_dart().into_dart(),
            self.capabilities.into_into_dart().into_dart(),
            self.sources.into_into_dart().into_dart(),
            self.best_endpoint.into_into_dart().into_dart(),
            self.candidate_endpoints.into_into_dart().into_dart(),
            self.candidate_count.into_into_dart().into_dart(),
            self.quarantined.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DiscoveryPeer {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiscoveryPeer> for crate::api::DiscoveryPeer {
    fn into_into_dart(self) -> crate::api::DiscoveryPeer {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiscoveryProviderStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::DiscoveryProviderStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiscoveryProviderStatus>
    for crate::api::DiscoveryProviderStatus
{
    fn into_into_dart(self) -> crate::api::DiscoveryProviderStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::HaloApiError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::HaloApiError::InvalidArgument { message } => {
                [0.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::HaloApiError::SessionNotFound => [1.into_dart()].into_dart(),
            crate::api::HaloApiError::Core { message } => {
                [2.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::HaloApiError::InternalState => [3.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::HaloApiError {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::HaloApiError> for crate::api::HaloApiError {
    fn into_into_dart(self) -> crate::api::HaloApiError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PairingBootstrap {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.listen_port.into_into_dart().into_dart(),
            self.identity_blob_to_persist.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PairingBootstrap
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PairingBootstrap>
    for crate::api::pairing_api::PairingBootstrap
{
    fn into_into_dart(self) -> crate::api::pairing_api::PairingBootstrap {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PairingEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event_id.into_into_dart().into_dart(),
            self.request_id.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.peer_presence_id.into_into_dart().into_dart(),
            self.peer_fingerprint.into_into_dart().into_dart(),
            self.short_code.into_into_dart().into_dart(),
            self.already_trusted.into_into_dart().into_dart(),
            self.authenticated_session_id.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PairingEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PairingEvent>
    for crate::api::pairing_api::PairingEvent
{
    fn into_into_dart(self) -> crate::api::pairing_api::PairingEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PairingEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Connecting => 0.into_dart(),
            Self::CodeAvailable => 1.into_dart(),
            Self::ConfirmationRequired => 2.into_dart(),
            Self::Trusted => 3.into_dart(),
            Self::Rejected => 4.into_dart(),
            Self::IdentityChanged => 5.into_dart(),
            Self::TimedOut => 6.into_dart(),
            Self::Cancelled => 7.into_dart(),
            Self::Failed => 8.into_dart(),
            Self::Disconnected => 9.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PairingEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PairingEventKind>
    for crate::api::pairing_api::PairingEventKind
{
    fn into_into_dart(self) -> crate::api::pairing_api::PairingEventKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PlatformPairingChannelState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Pending => 0.into_dart(),
            Self::Authenticated => 1.into_dart(),
            Self::Failed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PlatformPairingChannelState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PlatformPairingChannelState>
    for crate::api::pairing_api::PlatformPairingChannelState
{
    fn into_into_dart(self) -> crate::api::pairing_api::PlatformPairingChannelState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PlatformPairingRole {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Initiator => 0.into_dart(),
            Self::Responder => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PlatformPairingRole
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PlatformPairingRole>
    for crate::api::pairing_api::PlatformPairingRole
{
    fn into_into_dart(self) -> crate::api::pairing_api::PlatformPairingRole {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PlatformProviderState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Starting => 0.into_dart(),
            Self::Ready => 1.into_dart(),
            Self::Degraded => 2.into_dart(),
            Self::PermissionRequired => 3.into_dart(),
            Self::PermissionDenied => 4.into_dart(),
            Self::HardwareOff => 5.into_dart(),
            Self::Unsupported => 6.into_dart(),
            Self::TemporarilyUnavailable => 7.into_dart(),
            Self::Stopped => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::PlatformProviderState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PlatformProviderState>
    for crate::api::PlatformProviderState
{
    fn into_into_dart(self) -> crate::api::PlatformProviderState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::PlatformTlsIdentity {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.certificate_der.into_into_dart().into_dart(),
            self.private_key_x963.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::PlatformTlsIdentity
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::PlatformTlsIdentity>
    for crate::api::pairing_api::PlatformTlsIdentity
{
    fn into_into_dart(self) -> crate::api::pairing_api::PlatformTlsIdentity {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::TransferDirection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Sending => 0.into_dart(),
            Self::Receiving => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::TransferDirection
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::TransferDirection>
    for crate::api::pairing_api::TransferDirection
{
    fn into_into_dart(self) -> crate::api::pairing_api::TransferDirection {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::TransferEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event_id.into_into_dart().into_dart(),
            self.request_id.into_into_dart().into_dart(),
            self.authenticated_session_id.into_into_dart().into_dart(),
            self.transfer_id.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.file_name.into_into_dart().into_dart(),
            self.file_size.into_into_dart().into_dart(),
            self.transferred_bytes.into_into_dart().into_dart(),
            self.final_path.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::TransferEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::TransferEvent>
    for crate::api::pairing_api::TransferEvent
{
    fn into_into_dart(self) -> crate::api::pairing_api::TransferEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pairing_api::TransferEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::OfferReceived => 0.into_dart(),
            Self::AwaitingDecision => 1.into_dart(),
            Self::Transferring => 2.into_dart(),
            Self::Completed => 3.into_dart(),
            Self::Rejected => 4.into_dart(),
            Self::Cancelled => 5.into_dart(),
            Self::Failed => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pairing_api::TransferEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pairing_api::TransferEventKind>
    for crate::api::pairing_api::TransferEventKind
{
    fn into_into_dart(self) -> crate::api::pairing_api::TransferEventKind {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::pairing_api::AuthenticatedSessionInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.peer_fingerprint, serializer);
        <Option<String>>::sse_encode(self.peer_presence_id, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::DiscoveryBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.presence_id, serializer);
        <crate::api::DiscoveryDeviceType>::sse_encode(self.device_type, serializer);
        <Vec<u8>>::sse_encode(self.ble_presence, serializer);
    }
}

impl SseEncode for crate::api::DiscoveryDeviceType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::DiscoveryDeviceType::Unknown => 0,
                crate::api::DiscoveryDeviceType::Android => 1,
                crate::api::DiscoveryDeviceType::Ios => 2,
                crate::api::DiscoveryDeviceType::Macos => 3,
                crate::api::DiscoveryDeviceType::Windows => 4,
                crate::api::DiscoveryDeviceType::Linux => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::DiscoveryPeer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.presence_id, serializer);
        <crate::api::DiscoveryDeviceType>::sse_encode(self.device_type, serializer);
        <bool>::sse_encode(self.compatible, serializer);
        <u64>::sse_encode(self.capabilities, serializer);
        <Vec<String>>::sse_encode(self.sources, serializer);
        <Option<String>>::sse_encode(self.best_endpoint, serializer);
        <Vec<String>>::sse_encode(self.candidate_endpoints, serializer);
        <u32>::sse_encode(self.candidate_count, serializer);
        <bool>::sse_encode(self.quarantined, serializer);
    }
}

impl SseEncode for crate::api::DiscoveryProviderStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.state, serializer);
        <Option<String>>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::HaloApiError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::HaloApiError::InvalidArgument { message } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::HaloApiError::SessionNotFound => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::HaloApiError::Core { message } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::HaloApiError::InternalState => {
                <i32>::sse_encode(3, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::pairing_api::AuthenticatedSessionInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::pairing_api::AuthenticatedSessionInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::DiscoveryPeer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::DiscoveryPeer>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::DiscoveryProviderStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::DiscoveryProviderStatus>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <Vec<u8>>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::pairing_api::PairingEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::pairing_api::PairingEvent>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::pairing_api::TransferEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::pairing_api::TransferEvent>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::pairing_api::PairingBootstrap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.session_id, serializer);
        <u16>::sse_encode(self.listen_port, serializer);
        <Option<Vec<u8>>>::sse_encode(self.identity_blob_to_persist, serializer);
    }
}

impl SseEncode for crate::api::pairing_api::PairingEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.event_id, serializer);
        <Option<u64>>::sse_encode(self.request_id, serializer);
        <crate::api::pairing_api::PairingEventKind>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.peer_presence_id, serializer);
        <Option<String>>::sse_encode(self.peer_fingerprint, serializer);
        <Option<String>>::sse_encode(self.short_code, serializer);
        <bool>::sse_encode(self.already_trusted, serializer);
        <Option<u64>>::sse_encode(self.authenticated_session_id, serializer);
        <Option<String>>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::pairing_api::PairingEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pairing_api::PairingEventKind::Connecting => 0,
                crate::api::pairing_api::PairingEventKind::CodeAvailable => 1,
                crate::api::pairing_api::PairingEventKind::ConfirmationRequired => 2,
                crate::api::pairing_api::PairingEventKind::Trusted => 3,
                crate::api::pairing_api::PairingEventKind::Rejected => 4,
                crate::api::pairing_api::PairingEventKind::IdentityChanged => 5,
                crate::api::pairing_api::PairingEventKind::TimedOut => 6,
                crate::api::pairing_api::PairingEventKind::Cancelled => 7,
                crate::api::pairing_api::PairingEventKind::Failed => 8,
                crate::api::pairing_api::PairingEventKind::Disconnected => 9,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pairing_api::PlatformPairingChannelState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pairing_api::PlatformPairingChannelState::Pending => 0,
                crate::api::pairing_api::PlatformPairingChannelState::Authenticated => 1,
                crate::api::pairing_api::PlatformPairingChannelState::Failed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pairing_api::PlatformPairingRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pairing_api::PlatformPairingRole::Initiator => 0,
                crate::api::pairing_api::PlatformPairingRole::Responder => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::PlatformProviderState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::PlatformProviderState::Starting => 0,
                crate::api::PlatformProviderState::Ready => 1,
                crate::api::PlatformProviderState::Degraded => 2,
                crate::api::PlatformProviderState::PermissionRequired => 3,
                crate::api::PlatformProviderState::PermissionDenied => 4,
                crate::api::PlatformProviderState::HardwareOff => 5,
                crate::api::PlatformProviderState::Unsupported => 6,
                crate::api::PlatformProviderState::TemporarilyUnavailable => 7,
                crate::api::PlatformProviderState::Stopped => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pairing_api::PlatformTlsIdentity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.certificate_der, serializer);
        <Vec<u8>>::sse_encode(self.private_key_x963, serializer);
    }
}

impl SseEncode for crate::api::pairing_api::TransferDirection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pairing_api::TransferDirection::Sending => 0,
                crate::api::pairing_api::TransferDirection::Receiving => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::pairing_api::TransferEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.event_id, serializer);
        <Option<u64>>::sse_encode(self.request_id, serializer);
        <u64>::sse_encode(self.authenticated_session_id, serializer);
        <String>::sse_encode(self.transfer_id, serializer);
        <crate::api::pairing_api::TransferDirection>::sse_encode(self.direction, serializer);
        <crate::api::pairing_api::TransferEventKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.file_name, serializer);
        <u64>::sse_encode(self.file_size, serializer);
        <u64>::sse_encode(self.transferred_bytes, serializer);
        <Option<String>>::sse_encode(self.final_path, serializer);
        <Option<String>>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::pairing_api::TransferEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::pairing_api::TransferEventKind::OfferReceived => 0,
                crate::api::pairing_api::TransferEventKind::AwaitingDecision => 1,
                crate::api::pairing_api::TransferEventKind::Transferring => 2,
                crate::api::pairing_api::TransferEventKind::Completed => 3,
                crate::api::pairing_api::TransferEventKind::Rejected => 4,
                crate::api::pairing_api::TransferEventKind::Cancelled => 5,
                crate::api::pairing_api::TransferEventKind::Failed => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
