//! Narrow Flutter-facing API for Halo.
//!
//! Flutter receives product-ready snapshots from this crate. Native platform
//! drivers submit opaque operating-system observations here and never parse the
//! Halo protocol themselves.

#![deny(unsafe_code)]

mod api;
mod platform_socket;
// SAFETY: Android detaches one already-bound UDP file descriptor and transfers
// its ownership through this narrow JNI function. The descriptor is converted
// immediately into OwnedFd and no JNI pointer is dereferenced or retained.
#[cfg(target_os = "android")]
#[allow(unsafe_code)]
mod native_android;
// SAFETY: Apple Network.framework cannot expose its QUIC stream through the
// generated Dart API. This narrow C ABI validates every pointer and length
// before delegating to safe Rust pairing operations; no pointer is retained.
#[allow(unsafe_code)]
mod native_apple;
// SAFETY: This module is reproducibly generated by the pinned FFI generator.
// Unsafe pointer access is confined to its codec/runtime glue; Halo APIs remain
// safe Rust and the generated file is checked by CI for drift.
#[allow(unsafe_code)]
mod frb_generated;

pub use api::*;
