//! Narrow Flutter-facing API for Halo.
//!
//! Flutter receives product-ready snapshots from this crate. Native platform
//! drivers submit opaque operating-system observations here and never parse the
//! Halo protocol themselves.

#![deny(unsafe_code)]

mod api;
// SAFETY: This module is reproducibly generated by the pinned FFI generator.
// Unsafe pointer access is confined to its codec/runtime glue; Halo APIs remain
// safe Rust and the generated file is checked by CI for drift.
#[allow(unsafe_code)]
mod frb_generated;

pub use api::*;
